#-----------------------------------
--- # Application
#-----------------------------------

spring:
  application:
    name: APP_NAME
  profiles:
    active:
      - "@spring.profiles.active@"
  main:
    lazy-initialization: false
server:
  port: 8081

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
  main:
    lazy-initialization: true

#-----------------------------------
--- # i18n & L10n
#-----------------------------------

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages

#-----------------------------------
--- # Logging
#-----------------------------------

logging:
  level:
    com:
      tujuhsembilan: TRACE

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
logging:
  level:
    com:
      tujuhsembilan: INFO

#-----------------------------------
--- # Miscellanous
#-----------------------------------

spring:
  output:
    ansi:
      enabled: always

# # -----------------------------------
# --- #
# # -----------------------------------

#-----------------------------------
--- # Database
#-----------------------------------
spring:
  ## Datasource
  datasource:
    ## URL_INTERNAL
      # url: jdbc:postgresql://10.10.5.180:5432/new_db_talentcenter
    ## URL_EXTERNAL
    # url: jdbc:postgresql://cloudias79.com:5545/new_db_talentcenter
    # username: usrtalentcenter
    # password: m1QVs3zKymgPduz

    url: jdbc:postgresql://localhost:5432/talent_center2
    username: postgres
    password: wahyu260697
    driverClassName: org.postgresql.Driver
  ## Configuration
  jpa:
    ## database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # format_sql: true

# # -----------------------------------
# --- #
# # -----------------------------------

#-----------------------------------
--- # MinIO Configuration
#-----------------------------------
application:
  minio:
    url: https://minio.cloudias79.com/
    username: devtalentcenter
    password: as4Dx6L4Uf1zFkyy
    bucketName: talent-center-app
# # -----------------------------------
# --- #
# # -----------------------------------

#-----------------------------------
--- # servlet
#-----------------------------------
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


# # -----------------------------------
# --- #
# # -----------------------------------